#! /bin/sh
# Originally from libxml, Copyright (C) Daniel Veillard

prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${prefix}/lib/x86_64-linux-gnu

usage()
{
    cat <<EOF
Usage: clamav-config [OPTION]

Known values for OPTION are:

  --prefix=DIR		change libclamav prefix [default $prefix]
  --libs		print library linking information
  --cflags		print pre-processor and compiler flags
  --help		display this help and exit
  --version		output version information
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --version)
	echo 0.101.4
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
       	echo -I${prefix}/include -g -O2 -fdebug-prefix-map=/home/jordan/build/clamav-0.101.4=. -fstack-protector-strong -Wformat -Werror=format-security  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
       	;;

    --libs)
       	echo -L${prefix}/lib/x86_64-linux-gnu  -lz -lbz2
       	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0

